### ISSUE TITLE
Falta o return na função main

### ISSUE THREAD

**Issue by DavidGomesh** [DaveGomesh/TestandoIssues#1]
# Return na main
Se vc nao colocar o _return_ não vai funcionar.
**Sugestoes:**
- colocar o return
- deixar a funcao void

```c
#include <stdio.h>

int main(){
    printf("Primeira modificacao!\n");
}
```

**Comment by DaveGomesh** [comment]
# Ah, muito obrigado!
Vou tentar solucionar!

**Comment by DavidGomesh** [comment]
# Mas implementa logo!

**Comment by DaveGomesh** [comment]
> # Return na main
> Se vc nao colocar o _return_ não vai funcionar.
> **Sugestoes:**
> 
> * colocar o return
> * deixar a funcao void
> 
> ```c
> #include <stdio.h>
> 
> int main(){
>     printf("Primeira modificacao!\n");
> }
> ```

# Pronto, problema resolvido!
@DavidGomesh
